---
# tasks file for htpc-nas

# NFS Version 3 Server Installation and Configuration
- block:

  - name: Install NFS Server
    apt: name=nfs-kernel-server state=installed update_cache=yes cache_valid_time=3600

  - name: Configure NFS shares in /etc/exports
    lineinfile: dest=/etc/exports regexp='^{{ htpc_media_path }}' line='{{ htpc_media_path }} *(rw,insecure,all_squash,anonuid={{ htpc_user_uid }},anongid={{ htpc_user_gid }})'
    when: htpc_nas_nfs
    notify:
      - update nfs exports

  - name: Make sure NFS server is started on boot
    service: name=nfs-kernel-server state=started enabled=yes

  when: htpc_nas_nfs
  tags:
    - nfs

# SAMBA ( Windows File Sharing ) Installation and Configuration
- block:

  - name: Install SAMBA server
    apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
    with_items:
      - samba
      - samba-common
      - python-glade2

  - name: Update SAMBA configuration
    template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=644
    notify:
      - create samba users

  - name: Make sure SAMBA server is started on boot
    service: name=smbd state=started enabled=yes

  - name: Make sure SAMBA server is started on boot
    service: name=nmbd state=started enabled=yes

  when: htpc_nas_cifs
  tags:
    - cifs

# Netatalk ( Mac File Sharing ) Installation and Configuration
- block:

  - name: Install Netatalk
    apt: name=netatalk state=installed update_cache=yes cache_valid_time=3600

  - name: Update Netatalk Config
    template: src=afp.conf.j2 dest=/etc/netatalk/afp.conf owner=root group=root mode=0644 backup=yes
    notify:
      - restart netatalk

  - name: Enable Netatalk in /etc/default/netatalk
    template: src=default_netatalk.j2 dest=/etc/default/netatalk owner=root group=root mode=644
    notify:
      - restart netatalk

  - name: Enable Netatalk Service
    service: name=netatalk state=started enabled=yes

  when: htpc_nas_afp
  tags:
    - afp